Getting very close to being done
Entuned/Readr pull request #1
Opened 2021-12-04 01:18 UTC by hnavar

Component is almost done

2021-12-04 01:44 UTC, copelka requested changes

2021-12-04 01:44 UTC, copelka commented on client/src/components/AddFriend.jsx
> +/* eslint-disable */
disabling eslint in all of the files defeats the purpose of eslint

2021-12-04 01:44 UTC, copelka commented on client/src/components/BookGenreView.jsx
> +function BookGenreView() {
use ES6 instead of function declarations
`const BookGenreView = () => {}`

2021-12-04 01:44 UTC, copelka commented on client/src/components/Dropdown.jsx
> +  const onClickHorror = () => setGenre('horror') ;
keep working on functionality but think about how you can make this onClick block DRY

2021-12-04 01:44 UTC, copelka commented on config/passport-setup.js
> +    clientID: '831550743885-7a7f8m0t6pli22clvmresvbqg1uncdi1.apps.googleusercontent.com',
sensitive information should not be tracked/public - kill these credentials, make new ones, and add them to a gitignored file

2021-12-06 00:06 UTC, closed without merging

2021-12-06 00:06 UTC, hnavar commented
I am making a new request